name: Pull and Upload Curseforge Files

on:
  workflow_run:
    workflows: ["Setup repository"]
    types: [completed]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  pull_and_upload_files:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache BigWigs release.sh
        uses: actions/cache@v4
        with:
          path: release.sh
          key: release-sh-v1

      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: "pip"

      - run: pip install -r requirements.txt

      - name: Run Main Script
        run: python main.py
        env:
          ADDON_ID: 99982
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
